on:
  schedule:
  - cron: '0 0 * * *'
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  nginx-build:
    runs-on: ubuntu-latest
    name: NGINX build
    steps:
      - name: NGINX build
        uses: ./
